# Generated by Django 5.0.6 on 2024-06-20 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=255)),
            ],
            options={
                'db_table': 'CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=255)),
            ],
            options={
                'db_table': 'MODULO',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='TITULO', max_length=255)),
                ('data_abertura', models.DateTimeField(auto_now_add=True, db_column='DATAABERTURA')),
                ('data_encerramento', models.DateTimeField(auto_now_add=True, db_column='DATAENCERRAMENTO')),
                ('cliente', models.ForeignKey(db_column='CODCLIENTE', on_delete=django.db.models.deletion.CASCADE, to='dashboard.cliente')),
                ('modulo', models.ForeignKey(db_column='CODMODULO', on_delete=django.db.models.deletion.CASCADE, to='dashboard.modulo')),
            ],
            options={
                'db_table': 'TICKET',
            },
        ),
    ]
